# Generated by Django 4.1.5 on 2023-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("rating", models.IntegerField()),
                ("release_date", models.DateField()),
                (
                    "cover_photo",
                    models.ImageField(null=True, upload_to="service/covers/"),
                ),
                ("book_file", models.FileField(null=True, upload_to="service/files/")),
            ],
        ),
    ]
